services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "meubanco_db"
    volumes:
      # O banco.sql será executado na criação do banco
      - ./database/banco.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - toshiro-net

  php-app:
    build: ./backend
    deploy:
      replicas: 3 # MELHORIA: Cria 3 cópias do PHP rodando simultaneamente
    networks:
      - toshiro-net
    depends_on:
      - db

  proxy:
    build: ./proxy
    ports:
      - "4500:80" 
    depends_on:
      - php-app
    networks:
      - toshiro-net

networks:
  toshiro-net:
    driver: bridge

volumes:
  db_data: